### ISSUE TITLE
Bitte warte, bis die erforderlichen Spielinhalte bereit sind

### ISSUE THREAD

**Issue by BlueSky-fur** [eXo-OpenSource/mta-gamemode#1]
Vorweg erstmal respekt, und ich bin mir im klaren das hier vermutl. keiner mehr antworten wird.

Sieht nach einem Sehr sauberen gamemode aus, habe damals zur Anfangszeit auf eXo gespielt für ein paar Wochen, dann fehlte mir die zeit und jetzt wollte ich da mal wieder aus purer Nostalgie rumrennen :P 

Soweit läuft das ding auch, bis dann nach dem Verbinden der Bildschirm "Bitte warte, bis die erforderlichen Spielinhalte bereit sind..." kommt.

Davor musste man noch einige Links bestätigen für file-hoster etc, jedoch sind diese Links ja schon eine halbe Ewigkeit Offline, was wohl dazu führt das dieser Bildschirm nicht verschwindet, bzw die benötigten daten nicht heruntergeladen werden können.

Habe es jetzt Test-Weise mal knapp eine Stunde so gelassen aber kein Fortschritt.

Nun meine Frage, kommt man an die daten noch irgendwo oder kann man dieses System Aushebeln?

Ist ansich sehr schade da man das teil so nicht nutzen kann.

Lg, Ellie

**Comment by jushar** [comment]
Soweit ich mich erinnere, wird der (externe) HTTP-Download genutzt, um das Herunterladen zu beschleunigen. Die Dateien dafür werden über die Scripts im Ordner `build` erzeugt (siehe auch https://github.com/eXo-OpenSource/mta-gamemode/blob/master/Dockerfile).

Alternativ lässt sich dieses Verhalten aber auch abschalten, indem du `HTTP_DOWNLOAD` in nachfolgender Datei auf `false` setzt:
https://github.com/eXo-OpenSource/mta-gamemode/blob/master/vrp/client/constants.lua#L12

**Comment by BlueSky-fur** [comment]
Krass, das noch jemand antwortet :o 

Danke dir! :D Werde ich nachher mal testen und mich dann nochmal melden!

Ich wünsche einen schönen Tag und schonmal ein schönes Wochenende :p

**Comment by BlueSky-fur** [comment]
Hmm, hab es auf false gesetzt aber komme nachwievor wie oben beschrieben nicht weiter, wirft aber soweit auch keine errors aus

außer für das InfluxLogging, da hab ich die DB nicht importiert bekommen und noch nicht die zeit gefunden das zu fixen, könnte es auch daran liegen? 🤔 

Ich finde dazu online auch leider nichts hilfreiches, wenn ich die log-db versuche zu importieren kommt folgendes

```mysql
#1005 - Kann Tabelle `vrp_dev_logs`.`vrpLogs_ChatReceivers` nicht erzeugen (Fehler: 150 "Foreign key constraint is incorrectly formed")
``` 
wurde die eventuell falsch exportiert?

**Comment by MegaThorx** [comment]
> außer für das InfluxLogging, da hab ich die DB nicht importiert bekommen und noch nicht die zeit gefunden das zu fixen, könnte es auch daran liegen? 🤔

Das war ein externer Service und wird nicht benötigt.

> #1005 - Kann Tabelle `vrp_dev_logs`.`vrpLogs_ChatReceivers` nicht erzeugen (Fehler: 150 "Foreign key constraint is incorrectly formed")

Bist du auf Windows oder Linux? Bei der Migration gab es einen Fehler, welche dafür sorgt das dise unter Linux nicht geht. Bitte erneut probieren mit der aktualisierten Version.

> Soweit läuft das ding auch, bis dann nach dem Verbinden der Bildschirm "Bitte warte, bis die erforderlichen Spielinhalte bereit sind..." kommt.

@syynek sollte das Script soweit angepasst haben, dass der interne Downloader verwendet wird. Ggf die lokalen Logs checken.

**Comment by BlueSky-fur** [comment]
> Bist du auf Windows oder Linux? Bei der Migration gab es einen Fehler, welche dafür sorgt das dise unter Linux nicht geht. Bitte erneut probieren mit der aktualisierten Version.

Wenn du die DB meinst, das läuft auf Linux, hat jetzt funktioniert. :) (Der MTA Server läuft aber auf einer Windows Bare Metal)

> sollte das Script soweit angepasst haben, dass der interne Downloader verwendet wird. Ggf die lokalen Logs checken.

Prüfe ich dann gleich nochmal

**Comment by BlueSky-fur** [comment]
Wirft beim Serverstart einen Fehler aus

```
[10:55:26] WARNING: [vrp]\vrp\server\classes\Storage\MySQL.lua:14: dbPoll failed; Table 'vrp_dev_logs.vrpLogs_GameStats' doesn't exist
[10:55:26] INFO: [MySQL] dbPoll failed. Error code: 1146. Error message: nil
[10:55:26] ERROR: [vrp]\vrp\server\classes\StatisticsLogger.lua:367: bad argument #1 to 'pairs' (table expected, got boolean)
```

Die GameStats table existiert jedoch. gerade geprüft.

Nach einiger zeit spamt er auch folgendes
```
[11:05:36] WARNING: [vrp]\vrp\server\classes\InfluxLogging.lua:109: Bad argument @ 'utfSub' [Expected number at argument 3, got none]  [DUP x25]
```

Und beim zweiten error bin ich persönlich etwas ratlos. 😅 Zu lange her, wird zeit meine lua kentnisse wieder aufzufrischen >.<

**Comment by MegaThorx** [comment]
Lösche die Datenbank mal und führe die Migration nochmal vollständig durch. Das Problem liegt definitiv bei der Datenbank.

Kontrollier den Log ob _wirklich_ alle Tabellen erfolgreich angelegt wurden.

**Comment by BlueSky-fur** [comment]
Gerade gemacht, alles angelegt worden und nochmals gegengeprüft

**Comment by MegaThorx** [comment]
https://github.com/eXo-OpenSource/mta-gamemode/blob/master/vrp/server/config/config.json.dist

In der `config.json` die `database` bei `logs` und `premium` auf das selbe setzen wie bei `main`.

**Comment by BlueSky-fur** [comment]
Erledigt, errors sind nun verschwunden! Jedoch ist noch immer der Bildschirm da wie am anfang beschrieben und verschwindet nicht. Auch nachdem ich die lösungsansätze veruscht habe.


Dieser Influx error ist auch noch da, obwohl `DISABLE_INFLUX = true` gesetzt ist.
```
[11:05:36] WARNING: [vrp]\vrp\server\classes\InfluxLogging.lua:109: Bad argument @ 'utfSub' [Expected number at argument 3, got none]  [DUP x25]
```

Testweise habe ich in der `meta.xml` `InfluxLogging.lua` einmal auskommentiert, dann ists nurnoch ein Blackscreen.
Vermute also das durch diesen Error das ganze nicht "fertig läd"

**Comment by MegaThorx** [comment]
https://github.com/eXo-OpenSource/mta-gamemode/blob/master/vrp/server/classes/InfluxLogging.lua#L12-L13 die zwei Zeilen einfach auskommentieren

**Comment by BlueSky-fur** [comment]
Fehler wird nichtmehr gepostet, jedoch nach wie vor dieser Bildschirm hier, also leider nicht weitergekommen.

https://imgur.com/eN3MUDQ

**Comment by PeewX** [comment]
Schau mal ob im Client Log evt. Errors sind

**Comment by BlueSky-fur** [comment]
Im `clientscript.log` Ist folgendes zu sehen

```
[2023-07-07 14:05:42] WARNING: vrp\client\classes\Faction\Gangwar\GangwarDisplay.lua:30: File not found @ 'dxCreateTexture' [files/images/Gangwar/gradient.png]
[2023-07-07 14:06:12] WARNING: vrp\client\classes\InfluxLogging.lua:32: Bad argument @ 'utfSub' [Expected number at argument 3, got none]
[2023-07-07 14:06:18] WARNING: vrp\client\classes\InfluxLogging.lua:32: Bad argument @ 'utfSub' [Expected number at argument 3, got none]  [DUP x3]
```

Ich frage mich ob es an der GangwarDisplay.lua liegen könnte, aber das nur durch eine Textur das ganze teil nicht lädt wäre wiederum auch etwas unwahrscheinlich. 

Und ansonsten halt wieder der Influx Spaß

**Comment by MegaThorx** [comment]
Beides sind nur Warnmeldungen und sind nicht die Ursache für das Problem

**Comment by BlueSky-fur** [comment]
Ansonnsten gibt es leider keine fehler, nicht in der clientlog wedernoch im Serverlog.

Lösungsansätze alle abgeklappert ohne erfolg, bin jetzt echt etwas ratlos.

**Comment by BlueSky-fur** [comment]
Habe das ganze gerade nochmal frisch aufgesetzt, hänge am selben Problem, verstehe das ganze nicht da es halt auch 0 errors wirft. :/ 

Nur so am rande, sicherlich wurde es das, aber wurde das ganze einmal getestet auf funktionalität? 

Da fällt mir ein, es gibt ja auch z.b einen Build ordner in dem sachen compiled werden etc, kann es sein das ich da python u. docker nachinstallieren muss?

**Comment by BlueSky-fur** [comment]
Habe neue dinge herausgefunden!

In der log war ein error versteckt
```
[2023-07-07 20:54:02] ERROR: [vrp]\vrp\server\classes\Core.lua:84: attempt to index global 'StatisticsLogger' (a nil value)
```

Ich habe das ganze einmal auskommentiert, dann kam in der Konsole beim Serverstart viel mehr output. (ist das was wichtiges für den live betrieb, weil scheinbar geht es nur mit auskommentieren? 🤔 

```
[2023-07-07 20:56:53] Some files in 'vrp' use deprecated functions.
[2023-07-07 20:56:53] Use the 'upgrade' command to perform a basic upgrade of resources.
[2023-07-07 20:56:53] SyncMapElementData is now disabled
[2023-07-07 20:56:54] Initializing core...
[2023-07-07 20:56:54] Server password cleared
[2023-07-07 20:56:54] INFO: SERVER [TranslationManager:loadTranslation (25)] "Locale 'en' has been loaded!"
[2023-07-07 20:56:54] Created server bank account for job.trashman
[2023-07-07 20:56:54] Created server bank account for job.road_sweeper
[2023-07-07 20:56:54] Created server bank account for job.lumberjack
[2023-07-07 20:56:54] Created server bank account for job.farmer
[2023-07-07 20:56:54] Created server bank account for job.pizza_delivery
[2023-07-07 20:56:54] Created server bank account for job.heli_transport
[2023-07-07 20:56:54] Created server bank account for job.logistician
[2023-07-07 20:56:54] Created server bank account for job.fork_lift
[2023-07-07 20:56:54] Created server bank account for job.treasure_seeker
[2023-07-07 20:56:54] Created server bank account for job.gravel
[2023-07-07 20:56:54] Created server bank account for job.boxer
[2023-07-07 20:56:54] Created server bank account for action.bank_robbery
[2023-07-07 20:56:54] Created server bank account for group
[2023-07-07 20:56:54] Created server bank account for group.properties
[2023-07-07 20:56:54] INFO: Creating new Weapon-Table for Depot 2
[2023-07-07 20:56:54] INFO: Creating new Item-Table for Depot 2
[2023-07-07 20:56:54] INFO: Creating new Equipment-Table for Depot 2
[2023-07-07 20:56:54] WARNING: [vrp]\vrp\server\classes\Storage\MySQL.lua:14: dbPoll failed; Table 'vrp_dev.vrp_group_propKeys' doesn't exist
[2023-07-07 20:56:54] INFO: [MySQL] dbPoll failed. Error code: 1146. Error message: nil
[2023-07-07 20:56:54] INFO: Creating new Weapon-Table for Depot 3
[2023-07-07 20:56:54] INFO: Creating new Item-Table for Depot 3
[2023-07-07 20:56:54] INFO: Creating new Equipment-Table for Depot 3
[2023-07-07 20:56:54] WARNING: [vrp]\vrp\server\classes\Storage\MySQL.lua:14: dbPoll failed; Table 'vrp_dev.vrp_group_propKeys' doesn't exist
[2023-07-07 20:56:54] INFO: [MySQL] dbPoll failed. Error code: 1146. Error message: nil
[2023-07-07 20:56:54] INFO: Creating new Weapon-Table for Depot 4
[2023-07-07 20:56:54] INFO: Creating new Item-Table for Depot 4
[2023-07-07 20:56:54] INFO: Creating new Equipment-Table for Depot 4
[2023-07-07 20:56:54] WARNING: [vrp]\vrp\server\classes\Storage\MySQL.lua:14: dbPoll failed; Table 'vrp_dev.vrp_group_propKeys' doesn't exist
[2023-07-07 20:56:54] INFO: [MySQL] dbPoll failed. Error code: 1146. Error message: nil
[2023-07-07 20:56:54] INFO: Creating new Weapon-Table for Depot 5
[2023-07-07 20:56:54] INFO: Creating new Item-Table for Depot 5
[2023-07-07 20:56:54] INFO: Creating new Equipment-Table for Depot 5
[2023-07-07 20:56:54] WARNING: [vrp]\vrp\server\classes\Storage\MySQL.lua:14: dbPoll failed; Table 'vrp_dev.vrp_group_propKeys' doesn't exist
[2023-07-07 20:56:54] INFO: [MySQL] dbPoll failed. Error code: 1146. Error message: nil
```

Hier versucht er jetzt auf eine table zuzugreifen die scheinbar nie erstellt wurde(es gab nicht einen error beim importieren der DB nachdem ich die gefixte version genutzt habe), ich werde diese erstellen und dann nochmal schauen, fortan bis eine antwort eurerseits kommt werde ich diese Nachricht editieren um Spam zu vermeiden *hätte mir auch früher auffallen können, entschuldige. :)*


//

Langsam vermute ich das die DB einfach falsch exportiert wurde, in der DB legt er tabellen an kleingeschrieben wie "worlditems" z.b

Das Scipt sucht aber nach "WorldItems" mit 2 Großbuchstaben und da findet er die tabelle dann nicht, wenn ich jedoch im script das dann alles klein schreibe findet er es und springt zur nächsten tabelle die ärger macht, na das kann dauern xD

Und dann ständig dieser StatisticsLogger, kann man den irgendwie fixen oder muss ich denn ganz simpel überall raus nehmen?

**Comment by MegaThorx** [comment]
Welche Version von MTA verwendest du?

**Comment by BlueSky-fur** [comment]
> Welche Version von MTA verwendest du?

Die neuste für Client u. Server (server auf Windows, MariaDB auf Ubuntu)

**Comment by BlueSky-fur** [comment]
Ich hab die meisten StatsLogger jetzt auskommentiert, dann gehts weiter mit anderen errors 
```
[22:35:53] WARNING: [vrp]\vrp\server\classes\Vehicles\Super\PermanentVehicle.lua:225: Bad argument @ 'utfSub' [Expected number at argument 3, got none]
[22:35:53] ERROR: server\classes\Vehicles\Super\PermanentVehicle.lua:225: attempt to concatenate a boolean value
```

Langsam bin ich echt am verzweifeln, ich wüsste aber so auf die schnelle auch nicht wie ich den statslogger fixen soll.

**Comment by BlueSky-fur** [comment]
Ich überbringe gute nachrichten!

Habe MariaDB nun auf dem Windows Host installiert, DB Importiert, gamemode neu runtergeladen und importiert, der einzige error den ich gerade noch bekomme ist folgender 
```
[2023-07-07 23:02:53] WARNING: [vrp]\vrp\server\classes\Vehicles\GPS\GPS.lua:14: GPS module not loaded. Continuing without...
[2023-07-07 23:02:53] WARNING: [vrp]\vrp\server\classes\Vehicles\Super\PermanentVehicle.lua:225: Bad argument @ 'utfSub' [Expected number at argument 3, got none]
[2023-07-07 23:02:53] ERROR: server\classes\Vehicles\Super\PermanentVehicle.lua:225: attempt to concatenate a boolean value
```

Testweise auskommentiert, dann geht der selbe error bei CompanyVehicle los, irgendwas will da nicht beim Kennzeichen setzen kram, hab jetzt alles mit plates auskommentiert und siehe da, jetzt schreibt er gerade die daten auf die Festplatte! :D

Edit 2 //

Ich hab nen Login Bildschirm!!!!

Edit 3 //

Account angelegt, kann rumrennen und scheinbar spielen, aber das mit den Kennzeichen sollte man sich eventuell mal nähher anschauen, sollte ich weitere fehler finden melde ich mich.

Schreibe später nochmal ausführlich wie ich es jetzt nach frischer installation zum laufen bekommen habe falls andere da auch mal feststecken

Das GPS Modul ist ja nur eine Warnung, kann man das noch irgendwie aktivieren? :) 


Jetze muss ich nurnoch rausfinden wo in der DB ich mich zum admin setze dann passt soweit alles glaub ich


Aber endlich einen ziemlichen schritt weiter! 🥳

**Comment by BlueSky-fur** [comment]
Könnte mir eventuell jemand nen Tipp geben wie ich mir die höchsten Admin rechte gebe? ich hab in die DB geschaut werde daraus aber nicht schlau ob das jetzt die GroupID oder Rank oder sowas ist 😅 

Und allgemeine Frage, das Controlpanel habt ihr ja auch hochgeladen, das könnte ich ja theoretisch einbinden.

Website etc ist down da weiß ich bescheid :p 

Könnte ich auch die ganzen TS funktionalitäten wieder zum leben erwecken theoretisch? 🤔

**Comment by Maurice1143** [comment]
> Habe MariaDB nun auf dem Windows Host installiert, DB Importiert, gamemode neu runtergeladen und importiert, der einzige error den ich gerade noch bekomme ist folgender
> 
> ```
> [2023-07-07 23:02:53] WARNING: [vrp]\vrp\server\classes\Vehicles\GPS\GPS.lua:14: GPS module not loaded. Continuing without...
> [2023-07-07 23:02:53] WARNING: [vrp]\vrp\server\classes\Vehicles\Super\PermanentVehicle.lua:225: Bad argument @ 'utfSub' [Expected number at argument 3, got none]
> [2023-07-07 23:02:53] ERROR: server\classes\Vehicles\Super\PermanentVehicle.lua:225: attempt to concatenate a boolean value
> ```
> 
> Testweise auskommentiert, dann geht der selbe error bei CompanyVehicle los, irgendwas will da nicht beim Kennzeichen setzen kram, hab jetzt alles mit plates auskommentiert und siehe da, jetzt schreibt er gerade die daten auf die Festplatte! :D

Ich denke mal dein Sever läuft auf der Version 1.6?

> Das GPS Modul ist ja nur eine Warnung, kann man das noch irgendwie aktivieren? :)

Das GPS Modul und eine Anleitung zum installieren findest du hier https://github.com/eXo-OpenSource/ml_pathfind

> Könnte mir eventuell jemand nen Tipp geben wie ich mir die höchsten Admin rechte gebe? ich hab in die DB geschaut werde daraus aber nicht schlau ob das jetzt die GroupID oder Rank oder sowas ist 😅

Einen Rang gibst du dir in der Datenbank unter vrp_account in der Spalte Rank (9 ist Projektleiter)

**Comment by BlueSky-fur** [comment]
Super, danke euch das ihr mich ertragen habt :P 

Soweit läuft alles super! :D und ja der Server läuft auf der 1.6^^

**Comment by Maurice1143** [comment]
> Super, danke euch das ihr mich ertragen habt :P
> 
> Soweit läuft alles super! :D und ja der Server läuft auf der 1.6^^

Das Script sollte nun kompatibel mit der 1.6 sein.
Sollte noch etwas auftreten, melde dich einfach.

**Comment by BlueSky-fur** [comment]
Ach super! 

Ich schau dann gleich mal und setze nochmal nen testserver auf.

Bezüglich der TS und Control-Panel geschichte, das ist ja anfürsich nur den ganzen kram einbinden, sollte also generell easy möglich sein? 🤔 

Habe mir gerade auch das Control-Panel angesehen, werde da mal schauen ob ich den container zum laufen bekomme

**Comment by BlueSky-fur** [comment]
Mir ist gerade ein Problem mit den häusern aufgefallen, wenn man eines kauft, und reingeht wird man zwar in die angegebene dimension geschmissen, aber wird nicht ins haus teleportiert sondern irgendwo in der Stadt auf die straße.

Könnte es sein das da die Teleporter etwas broken sind?

**Comment by Maurice1143** [comment]
> Mir ist gerade ein Problem mit den häusern aufgefallen, wenn man eines kauft, und reingeht wird man zwar in die angegebene dimension geschmissen, aber wird nicht ins haus teleportiert sondern irgendwo in der Stadt auf die straße.
> 
> Könnte es sein das da die Teleporter etwas broken sind?

Moin!
Ich konnte es bei mir nicht reproduzieren, kannst du vielleicht ein Video oder genauere Informationen (HausId) mitteilen?

**Comment by BlueSky-fur** [comment]
Aber gerne doch, mache ich morgen!

**Comment by BlueSky-fur** [comment]
> > Mir ist gerade ein Problem mit den häusern aufgefallen, wenn man eines kauft, und reingeht wird man zwar in die angegebene dimension geschmissen, aber wird nicht ins haus teleportiert sondern irgendwo in der Stadt auf die straße.
> > Könnte es sein das da die Teleporter etwas broken sind?
> 
> Moin! Ich konnte es bei mir nicht reproduzieren, kannst du vielleicht ein Video oder genauere Informationen (HausId) mitteilen?

https://www.youtube.com/watch?v=lVIU883NH44 Hier einmal der link 


Die houseid ist die 8 wenn ich mich nicht täusche!

**Comment by Maurice1143** [comment]
> > > Mir ist gerade ein Problem mit den häusern aufgefallen, wenn man eines kauft, und reingeht wird man zwar in die angegebene dimension geschmissen, aber wird nicht ins haus teleportiert sondern irgendwo in der Stadt auf die straße.
> > > Könnte es sein das da die Teleporter etwas broken sind?
> > 
> > 
> > Moin! Ich konnte es bei mir nicht reproduzieren, kannst du vielleicht ein Video oder genauere Informationen (HausId) mitteilen?
> 
> https://www.youtube.com/watch?v=lVIU883NH44 Hier einmal der link
> 
> Die houseid ist die 8 wenn ich mich nicht täusche!

Kann es sein, dass du die Interior Id des Hauses geändert hast?
Falls ja, würde ich dir empfehlen es wieder zu ändern, dass dieses Interior meines Wissens nach, nicht für die Verwendung bei Häusern gedacht war.

**Comment by BlueSky-fur** [comment]
Die InteriorID habe ich nicht angefasst, war default so.

**Comment by BlueSky-fur** [comment]
Wollte hier mal fragen bezüglich des Scripts.

Ich hatte vor demnächst anzufangen das MTA Voicechat script zu kopieren, und so umzubauen das es mit dem eXo script läuft und auch mit Fraktions-Chat und Staats-Funk usw. 

Kann ich da dann eine PR machen wenn das ganze z.b via config an und abgeschaltet werden kann, so wird das zwar hinzugefügt, aber man kann noch immer aussuchen ob man das nutzen will oder nicht.

Ansonsten mach ich es als neue branch^^

Habe die idee heute morgen bekommen und es ist ein guter wieder-einstieg in Lua, damit ich da wieder Fit werde, bin sehr eingerostet :P

**Comment by StiviiK** [comment]
Wir schauen uns jede Verbesserung unseres Scriptes gerne an und wenn es dazu passt nehmen wir das auf.

Ein PR ist der beste Weg bei uns Vorschläge / Verbesserungen zu implementieren.

Wir freuen uns über jede Verbesserung 😄

**Comment by BlueSky-fur** [comment]
Alles klar 😄 Wenn das ganze dann fertig ist mach ich nen PR :)
