### ISSUE TITLE
Server Password

### ISSUE THREAD

**Issue by weewoo-meow** [eXo-OpenSource/mta-gamemode#2]
Hello, how is it possible to add a server password when installing it from Docker?

**Comment by syynek** [comment]
Hey, there is currently no way to add a server password in the docker-compose file (You can submit a PR for this!), but you can add it to the database.

You can enter it in the row `ServerPassword` in the column `vrp_settings`.

**Comment by weewoo-meow** [comment]
Thank you for the hint, I can make later some contributions mainly for Docker and web technologies except Woltlab.

BTW: How do I buy a house?

**Comment by syynek** [comment]
You walk to a house marker and press F.

**Comment by weewoo-meow** [comment]
Ok, houses and buildings are not the same.
